import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/layout/Header';

const degular = localFont({
  src: [
    {
      path: './fonts/DegularDemo-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/DegularDemo-Semibold.otf',
      weight: '600',
      style: 'normal',
    }
  ],
})

export const metadata: Metadata = {
  title: 'Main Stack',
  description: 'Generated by create next app and developed by michael'
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ degular.className }>
         <Header />
        <main className='max-w-[1100px] mx-auto'>
          
        { children }
         </main>
      </body>
    </html>
  )
}
